// Mock for Leaflet — Leaflet uses browser APIs (window, document) not in jsdom
module.exports = {
  map: jest.fn(() => ({
    setView: jest.fn().mockReturnThis(),
    addLayer: jest.fn().mockReturnThis(),
    removeLayer: jest.fn().mockReturnThis(),
    on: jest.fn().mockReturnThis(),
    off: jest.fn().mockReturnThis(),
    remove: jest.fn(),
    getBounds: jest.fn(() => ({ contains: jest.fn() })),
    getZoom: jest.fn(() => 12),
    setZoom: jest.fn().mockReturnThis(),
    panTo: jest.fn().mockReturnThis(),
    fitBounds: jest.fn().mockReturnThis(),
    invalidateSize: jest.fn(),
    getContainer: jest.fn(() => document.createElement('div')),
  })),
  tileLayer: jest.fn(() => ({ addTo: jest.fn().mockReturnThis() })),
  marker: jest.fn(() => ({
    addTo: jest.fn().mockReturnThis(),
    bindPopup: jest.fn().mockReturnThis(),
    on: jest.fn().mockReturnThis(),
    setLatLng: jest.fn().mockReturnThis(),
    remove: jest.fn(),
  })),
  circleMarker: jest.fn(() => ({
    addTo: jest.fn().mockReturnThis(),
    bindPopup: jest.fn().mockReturnThis(),
    on: jest.fn().mockReturnThis(),
    remove: jest.fn(),
    setStyle: jest.fn(),
  })),
  circle: jest.fn(() => ({
    addTo: jest.fn().mockReturnThis(),
    remove: jest.fn(),
    setStyle: jest.fn(),
  })),
  polygon: jest.fn(() => ({
    addTo: jest.fn().mockReturnThis(),
    bindPopup: jest.fn().mockReturnThis(),
    on: jest.fn().mockReturnThis(),
    remove: jest.fn(),
    setStyle: jest.fn(),
  })),
  layerGroup: jest.fn(() => ({
    addTo: jest.fn().mockReturnThis(),
    addLayer: jest.fn().mockReturnThis(),
    removeLayer: jest.fn().mockReturnThis(),
    clearLayers: jest.fn().mockReturnThis(),
  })),
  featureGroup: jest.fn(() => ({
    addTo: jest.fn().mockReturnThis(),
    addLayer: jest.fn().mockReturnThis(),
    clearLayers: jest.fn().mockReturnThis(),
    getBounds: jest.fn(() => ({})),
  })),
  icon: jest.fn(() => ({})),
  divIcon: jest.fn(() => ({})),
  latLng: jest.fn((lat, lng) => ({ lat, lng })),
  latLngBounds: jest.fn(() => ({
    contains: jest.fn(),
    extend: jest.fn(),
    isValid: jest.fn(() => true),
  })),
  popup: jest.fn(() => ({
    setLatLng: jest.fn().mockReturnThis(),
    setContent: jest.fn().mockReturnThis(),
    openOn: jest.fn().mockReturnThis(),
  })),
  Control: {
    extend: jest.fn(() => ({ addTo: jest.fn() })),
  },
  DomUtil: {
    create: jest.fn(() => document.createElement('div')),
    addClass: jest.fn(),
    removeClass: jest.fn(),
  },
  DomEvent: {
    on: jest.fn(),
    off: jest.fn(),
    stopPropagation: jest.fn(),
    preventDefault: jest.fn(),
  },
};
